[package]
name = "revim"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]
description = "A vim like text editor written in rust"

[[bin]]
name = "rv"
path = "src/main.rs"

[dependencies]
termion = "1.5"
error-chain = "0.11.0-rc.2"
clap = "2.26"
